### PR TITLE
Update 99 julia usage

### PR DESCRIPTION
**Pull request by terasakisatoshi**

### CODE REVIEW

**Comment by Dale-Black** [comment]
Any luck getting job offerings with Julia info? E.g. LinkedIn, Indeed, etc?

**Review by Dale-Black — CHANGES_REQUESTED** [review]
Let's wait until we add some of the job scrapings to merge this PR

**Comment by terasakisatoshi** [comment]
> Let's wait until we add some of the job scrapings to merge this PR

You mean https://github.com/Glass-Notebook/GlassBlog/pull/3/files ?

**Comment by Dale-Black** [comment]
> > Let's wait until we add some of the job scrapings to merge this PR
> 
> You mean https://github.com/Glass-Notebook/GlassBlog/pull/3/files ?

Oh yes, I missed that. Ideally this would be included in 1 PR but if 2 is better that is okay

**Comment by terasakisatoshi** [comment]
Thank you! 😄

**Pull request merged**
